trustedProxies:
  - "10.244.0.0/16"
publicIP: "192.168.8.10"
artifactsFileServer: "http://artifact-server.tinkerbell.svc.cluster.local:80"

hegel:
  image:
    tag: "v0.9.0"

smee:
  image:
    tag: "v0.9.0"

tink:
  image:
    tag: "v0.9.0"

hook:
  enabled: true

artifactServer:
  enabled: false