apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-components-config
  namespace: argocd
spec:
  generators:
    - list:
        elements:

          - name: rook
            wave: "0"
            repoURL: "https://github.com/evoteum/kubernetes-lab-config.git"
            path: "components/rook"
            revision: "main"
            namespace: "rook-ceph"
            prune: true

          - name: gateway-api-config
            wave: "0"
            repoURL: "https://github.com/evoteum/kubernetes-lab-config.git"
            path: "components/gatewayapi"
            revision: "main"
            namespace: "gateway-api-system"

          - name: metallb-config
            wave: "1"
            repoURL: "https://github.com/evoteum/kubernetes-lab-config.git"
            path: "components/metallb"
            revision: "main"
            namespace: "metallb-system"

  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "{{wave}}"
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        targetRevision: "{{revision}}"
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
