apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/evoteum/kubernetes-lab-config.git
    path: platform/gateway
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-api-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
